### ISSUE TITLE
Problem with fontFamily

### ISSUE THREAD

**Issue by ElRochito** [FokkeZB/nl.fokkezb.html2as.widget#1]
I've a problem when I set a fontFamily on your widget.
When I set this :
font: {
    fontSize: 14,
    fontFamily: "SegoeUI"
}
No event from link was fired, I didn't receive an event in order to open in Safari.

When I remove fontFamily property it's works fine!

Do you have encountered this problem ?

Thanks

**Comment by FokkeZB** [comment]
That's very, very weird... if you use `Helvetica Neue` (the default) as fontFamily it does work?

**Comment by ElRochito** [comment]
Works fine with any fontFamily and Helvetica Neue.
Maybe SegoeUI font have a problem but works on my app on Label, TextField etc ..
I've embedded correctly my fonts in tiapp.xml yet.
My tiapp.xml looks like :
![tiapp](https://cloud.githubusercontent.com/assets/1737307/6096578/1034ffe6-af99-11e4-8353-0206d649fc17.png)

**Comment by FokkeZB** [comment]
Well, if it works other font families then I'm pretty confident to say it's not the module/widget but the font.

By the way.. no need to include your fonts in `tiapp.xml`. Titanium will add automatically add all fonts in the font dir to the `Info.plist` for you.
