### ISSUE TITLE
Event tap, click ...

### ISSUE THREAD

**Issue by ElRochito** [FokkeZB/nl.fokkezb.html2as.widget#2]
It's possible to have an event click or tap dispatch instead of longtap when listening 'link' ?

For any people, it's hard to know they have to long tap to open url

**Comment by FokkeZB** [comment]
That's currently not possible because of a limitation in the Titanium API. Please see the new [Known issues](https://github.com/FokkeZB/nl.fokkezb.html2as.widget/blob/master/README.md#known-issues) section I added.

**Comment by ElRochito** [comment]
Great!
Thank you!
