### ISSUE TITLE
<li> <ul> Html tags aren't recognized

### ISSUE THREAD

**Issue by annamf** [FokkeZB/nl.fokkezb.html2as.widget#4]
Hello,

I'm using this widget on iOS and the `<ul>` and `<li>` tags aren't recognized by the widget. And for iOS `\n` and `\t` aren't recognized too. It's possible to add this?

Thank you.

**Comment by FokkeZB** [comment]
Hello @annamf,

I don't think it's possible to create lists using [Attributed Strings](http://docs.appcelerator.com/platform/latest/#!/guide/Attributed_Strings), at least in Titanium.

The other point is discussed in #3 

Thanks!
